# Generated by Django 4.2.1 on 2023-05-21 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_name', models.CharField(max_length=40)),
                ('bundle', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(max_length=20)),
                ('s_location', models.CharField(max_length=120)),
                ('s_category', models.CharField(max_length=30)),
                ('s_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owns', to='mahallak.merchant')),
            ],
        ),
    ]
