# Generated by Django 4.2.1 on 2023-05-21 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mahallak', '0002_merchant_m_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=20)),
                ('c_location', models.CharField(max_length=120)),
                ('c_email', models.EmailField(default='', max_length=254)),
                ('c_pass', models.CharField(max_length=40)),
            ],
        ),
        migrations.RenameField(
            model_name='store',
            old_name='s_category',
            new_name='s_speciality',
        ),
        migrations.AddField(
            model_name='merchant',
            name='m_pass',
            field=models.CharField(default='NULL', max_length=40),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=20)),
                ('p_price', models.FloatField()),
                ('p_category', models.CharField(max_length=30)),
                ('p_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owns', to='mahallak.store')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('o_address', models.CharField(max_length=120)),
                ('o_price', models.FloatField()),
                ('o_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buying', to='mahallak.customer')),
                ('o_products', models.ManyToManyField(related_name='isin', to='mahallak.product')),
            ],
        ),
    ]
