# Generated by Django 4.2.1 on 2023-05-21 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahallak', '0003_customer_rename_s_category_store_s_speciality_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=40)),
                ('cat_produts', models.ManyToManyField(blank=True, related_name='isa', to='mahallak.product')),
            ],
        ),
    ]
