# Generated by Django 4.2.1 on 2023-05-21 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mahallak', '0004_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Categorie',
        ),
    ]
