# Generated by Django 4.2.1 on 2023-05-21 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mahallak', '0005_rename_category_categorie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorie',
            name='cat_produts',
        ),
        migrations.AlterField(
            model_name='product',
            name='p_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='isa', to='mahallak.categorie'),
        ),
        migrations.AlterField(
            model_name='store',
            name='s_speciality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soldat', to='mahallak.categorie'),
        ),
    ]
