# Generated by Django 4.2.1 on 2023-05-21 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mahallak', '0006_remove_categorie_cat_produts_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='s_speciality',
            new_name='s_category',
        ),
    ]
