# Generated by Django 4.2.1 on 2023-05-30 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahallak', '0007_alter_offer_product_alter_orderdetail_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
