# Generated by Django 4.2.1 on 2023-05-30 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mahallak', '0013_remove_order_store_orderdetail_store'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='store',
        ),
    ]
