# Generated by Django 4.2.1 on 2023-05-31 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mahallak', '0014_remove_orderdetail_store'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchant',
            name='bundle',
        ),
    ]
